cuberite:
  build: ./cuberite
  container_name: minecraft
  hostname: minecraft
  ports:
    - "25565:25565"
    - "9080:8080"
  tty: true
  stdin_open: true
  restart: always
  volumes:
    - ./cuberite/data:/data

pocketmine:
  build: ./pocketmine
  container_name: pocketmine
  hostname: pocketmine
  ports:
    - "19132:19132/udp"
  restart: always
  volumes:
    - ./pocketmine/data:/pocketmine/worlds
