version: "3.9"
services:
  mc:
    image: itzg/minecraft-server
    container_name: mc
    hostname: mc
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      MEMORY: "4G"
      TYPE: "PAPER"
      RCON_PASSWORD: ${RCON_PASSWORD:-minecraft}
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - ./mc/data:/data

  rcon:
    image: itzg/rcon
    container_name: rcon
    hostname: rcon
    ports:
      - "4326:4326"
      - "4327:4327"
    environment:
      RWA_RCON_HOST: mc
      RWA_RCON_PASSWORD: ${RCON_PASSWORD:-minecraft}
      RWA_PASSWORD: ${RCON_PASSWORD:-minecraft}
    volumes:
      - "./rcon/data:/opt/rcon-web-admin/db"

  bds:
    image: itzg/minecraft-bedrock-server
    container_name: bds
    hostname: bds
    ports:
      - 19132:19132/udp
    environment:
      EULA: "TRUE"
      GAMEMODE: survival
      DIFFICULTY: normal
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - ./bds/data:/data
